language: java
script: mvn clean package
jdk:
  - oraclejdk8
os:
  - linux
#deploy:
#  provider: releases
#  api_key: "GITHUB OAUTH TOKEN"
#  file: "/target/my-rest-service.jar"
#  skip_cleanup: true
#  on:
#    tags: true